### ISSUE TITLE
How to specify connadline flags?

### ISSUE THREAD

**Issue by volkanunsal** [psyho/js-test-driver-rails#1]
For example: `captureConsole`

http://code.google.com/p/js-test-driver/wiki/CommandLineFlags

**Comment by psyho** [comment]
The current version does not allow passing the command line flags directly, but some are supported, including the --captureConsole flag. If you are using 0.5.0.pre5 version, than the way to do that is by running:

```
 jstd run --capture-console
```

You can see all possible commands via:

```
jstd help
```

and options via:

```
jstd help [command]
```

I have to warn you though, that the --captureConsole flag does not work in JsTestDriver as far as I know.
